# Prometheus Configuration for Trustworthy RAG System

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'trustworthy-rag'

scrape_configs:
  - job_name: 'rag-api'
    static_configs:
      - targets: ['rag-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

